version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: rag-chatbot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  chromadb:
    image: chromadb/chroma:latest
    container_name: rag-chatbot-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: MySQL database for persistent storage
  mysql:
    image: mysql:8.0
    container_name: rag-chatbot-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rag_chatbot
      MYSQL_USER: chatbot
      MYSQL_PASSWORD: chatbot_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    profiles:
      - database

volumes:
  redis_data:
  chromadb_data:
  mysql_data:
